name: flutter_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: ^7.1.3
  fluro: ^2.0.3

  # Annotations
  json_annotation: ^4.3.0
  freezed_annotation: ^1.0.0

  # State management
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

  # Network
  dio: ^4.0.0
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.4
  freezed: ^1.1.1

flutter:
  uses-material-design: true
